### ISSUE TITLE
Where is the GUI widgets?

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [ColleagueRiley/RGFW#10]
Hi
No doubt this looks like a new project in it's beginning, so well done for that.
GUI? I found a button, select and a slider. Maybe you should warn visitors that this is very alpha and the GUI part of the GUI toolkit has not yet been implemented :)

**Comment by ColleagueRiley** [comment]
Hello! You make a good point, however your issue has been posted in the wrong repo. 

The GUI library is RSGL, not RGFW. RGFW only handles window management and creation.
The RSGL repo can be found [here](https://github.com/ColleagueRiley/RSGL)
