### ISSUE TITLE
RGFW_window_getMousePoint() returns global point coordinates on X11

### ISSUE THREAD

**Issue by Code-Nycticebus** [ColleagueRiley/RGFW#16]
When tested on Linux/X11, `RGFW_window_getMousePoint()` and `RGFW_getGlobalMousePoint()` return the same values.

In the `RGFW_window_getMousePoint()` implementation for X11 (line 2711), the second argument to `XQueryPointer` should be `win->src.window`, not `XDefaultRootWindow((Display*) win->src.display)`.

### Current Code
```c
XQueryPointer((Display*) win->src.display, XDefaultRootWindow((Display*) win->src.display), &window1, &window2, &x, &y, &RGFWMouse.x, &RGFWMouse.y, &z);
```

### Proposed Change
```c
XQueryPointer((Display*) win->src.display, win->src.window, &window1, &window2, &x, &y, &RGFWMouse.x, &RGFWMouse.y, &z);
```

**Comment by ColleagueRiley** [comment]
Thanks, I didn't notice that. You could've done a PR, but this is just as helpful.
