### ISSUE TITLE
wait events support?

### ISSUE THREAD

**Issue by anggape** [ColleagueRiley/RGFW#24]
currently im building a desktop app and see this library is a perfect replacement for glfw since i need to make my app run on windows xp, however the only thing that missing in this library is wait events support, is there any plans to add wait events similar to `glfwWaitEvents`, `glfwWaitEventsTimeout` and `glfwPostEmptyEvent`? thanks

**Comment by ColleagueRiley** [comment]
I'll have to look into those functions and see what they do. But you should also be able to work around them if you need to.

**Comment by ColleagueRiley** [comment]
These functions seem to exist to control GLFW's event queue. RGFW does not queue events, so I don't think these functions are needed.

**Comment by ColleagueRiley** [comment]
I think this can be implemented into

RGFW_window_checkEvents

However if you're using 

RGFW_window_checkEvent you will have to, and can easily, implement it yourself.

**Comment by ColleagueRiley** [comment]
@anggape I added the wait feature to `RGFW_window_checkEvents` Does this work as an alternative to those functions?

**Comment by anggape** [comment]
for some reason it uses more CPU instead of reducing it, in glfw the cpu usage will drop to 0 if it doesn't receive any events

https://github.com/user-attachments/assets/4521c01e-fb1d-403e-9f32-64eedb6cfdd9

**Comment by ColleagueRiley** [comment]
Thanks, I'll try to fix that.

**Comment by ColleagueRiley** [comment]
When I tried testing it the numbers didn't get that high at all. But there also wasn't much of a difference between waiting and getting events.

**Comment by anggape** [comment]
here another example, when nothing happen it will drop to 0 in glfw

https://github.com/user-attachments/assets/c02706c7-0ff2-4781-a188-2c76db2d52c2

**Comment by ColleagueRiley** [comment]
It seems jumpy on RGFW. 

https://github.com/user-attachments/assets/06de1939-48c9-4046-84e5-75dd85f7e77d

**Comment by ColleagueRiley** [comment]
I think I know how to fix this issue for X11 at least.

**Comment by ColleagueRiley** [comment]
This should be fixed on X11, but I've not yet tested it for windows and macOS.

**Comment by ColleagueRiley** [comment]
@anggape I fixed the wait feature, the CPU performance should be as expected. I also added the function `RGFW_window_eventWait` for those who aren't using `RGFW_window_checkEvents`

**Comment by anggape** [comment]
thanks, i will check it out when im at the computer

**Comment by ColleagueRiley** [comment]
@anggape I’m going to close this issue since I’m pretty sure it’s solved. 

Feel free to re-open it if I’m missing something.
