### ISSUE TITLE
Definition of RGFW_dxInfo is misplaced

### ISSUE THREAD

**Issue by Noxygen** [ColleagueRiley/RGFW#25]
RGFW_dxInfo gets defined on line 3915, however it is referenced by this block on line 1504:
```
#if defined(RGFW_WINDOWS) && defined(RGFW_DIRECTX)
	RGFW_dxInfo.pDeviceContext->lpVtbl->OMSetRenderTargets(RGFW_dxInfo.pDeviceContext, 1, &win->src.renderTargetView, NULL);
#elif defined(RGFW_OPENGL)
	RGFW_window_makeCurrent_OpenGL(win);
#endif
```
This results in compilation errors for DX11. Moving the definition of RGFW_dxInfo further up solves the issue.

**Comment by ColleagueRiley** [comment]
Oh, I didn't check DirectX after I reorganized this part. Thanks for telling me. 

https://github.com/ColleagueRiley/RGFW/commit/e769e91ebdd7a315fd17d2ce80a69477dc8bad28
