### ISSUE TITLE
Metal support

### ISSUE THREAD

**Issue by pusewicz** [ColleagueRiley/RGFW#26]
Will there be support for Metal on macOS/iOS?

**Comment by ColleagueRiley** [comment]
Probably, although that is far from being a priority. 

You might be able to add `#define RGFW_NO_API` and then set up your  Metal context. However, I've never used Mtal so I don't know if it works that way.

**Comment by ColleagueRiley** [comment]
@pusewicz  I made an external example for using RGFW with metal https://github.com/RSGL/RGFW-Metal

**Comment by ricardobeat** [comment]
Looks like that repo is unreachable, has it moved somewhere else?

**Comment by ColleagueRiley** [comment]
@ricardobeat Yes, it was moved into RGFW after this (https://github.com/ColleagueRiley/RGFW/pull/38) pull request. https://github.com/ColleagueRiley/RGFW/blob/main/examples/metal/metal.m
