### ISSUE TITLE
Invalid use of GLX_USE_GL, Failed to find any valid GLX configs

### ISSUE THREAD

**Issue by Zettexe** [ColleagueRiley/RGFW#27]
The `GLX_USE_GL` attribute seems to be causing no GLX configs to be found on my system, simply commenting out `RGFW_GL_USE_OPENGL,		1,` from `RGFW_initAttribs` seems to fix it for me. Suspecting it may have been accidentally taken from `glXChooseVisual` since that function can actually take a `GLX_USE_GL` attribute while `glXChooseFBConfig` cannot.

**Comment by ColleagueRiley** [comment]
I've not had this issue, so I'll look into it before I fix it. Thank you for reporting the issue.

**Comment by ColleagueRiley** [comment]
> Suspecting it may have been accidentally taken from glXChooseVisual since that function can actually take a GLX_USE_GL attribute while glXChooseFBConfig cannot.

This makes sense

**Comment by ColleagueRiley** [comment]
https://github.com/ColleagueRiley/RGFW/commit/6ee5ff92fd7ada895f66050e5f166cb859552f29

fixes this issue
