### ISSUE TITLE
Unused return value

### ISSUE THREAD

**Issue by Zettexe** [ColleagueRiley/RGFW#28]
Not really a big issue, but an annoyance nonetheless.

`RGFW.h:4030:25: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]`

**Comment by ColleagueRiley** [comment]
This should be fixed with this commit https://github.com/ColleagueRiley/RGFW/commit/39ce5cc57a282e938c45382f45d82bb74c9f788b 

Although I don't get that warning so I'm not sure if it's fixed.

**Comment by Zettexe** [comment]
Yep, that fixes it. Might be a compiler specific thing as I am using gcc.
