### ISSUE TITLE
Monitor scale values seem to be wrong.

### ISSUE THREAD

**Issue by jarroddavis68** [ColleagueRiley/RGFW#33]
When I created a window that is set to scale to monitor DPI, the 800x600 window was way too big. My 4k monitor is scaled at 150%, with a DPI of 144, thus the scale factor would be 1.5, but it returns 2.76 thus the window scale is larger than it should be. 

In my own code I get 144 dpi, 1.5 scale (dividing 144/96.0). I resize by this value and the window is sized appropriately for the DPI.

I'm on win64, using opengl.

**Comment by ColleagueRiley** [comment]
Thank you for telling me. I'll be looking into this asap.

**Comment by jarroddavis68** [comment]
> Thank you for telling me. I'll be looking into this asap.

np.

Also, a few of the routines at the top do not have RGFWDEF on it so they won't get exported. I use this with Delphi so every update I have to remember to go in and add them.

**Comment by ColleagueRiley** [comment]
> Also, a few of the routines at the top do not have RGFWDEF on it so they won't get exported. I use this with Delphi so every update I have to remember to go in and add them.

Thanks, the RGFWDEF issue should be fixed now! 
Let me know if you find any more issues.

**Comment by jarroddavis68** [comment]
> Thanks, the RGFWDEF issue should be fixed now!
> Let me know if you find any more issues.

Coolness. Thanks.

**Comment by ColleagueRiley** [comment]
I'm not sure where the 2.76 scale is coming from, based on my tests the scale was always 1 because DPIAware was not enabled. It's now enabled via [`SetProcessDPIAware`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware). Let me know if the issue still occurs.

**Comment by jarroddavis68** [comment]
Sadly, I'm getting the same value. The window is scaled by 2.76 rather than 1.5.

https://github.com/user-attachments/assets/e345405b-042a-4378-8835-1a5d9cfd0d56

**Comment by ColleagueRiley** [comment]
I was getting the proper values on my side. Although based on the documentation, that makes sense.

I'm not sure why the scale function isn't working, I'll look into it later today.

**Comment by ColleagueRiley** [comment]
I was getting the proper values on my side. Although based on the documentation, that makes sense.

I'm not sure why the scale function isn't working, I'll look into it later today.

**Comment by ColleagueRiley** [comment]
`RGFW_window_scaleToMonitor` doesn't work because the code looks something like this

`((u32)scale) * width`, (u32)scale would == 1

I'm changing it to look like this

(u32)(scale * (float)width)

Rather than rounding the value.

**Comment by jarroddavis68** [comment]
Ok, yea, that worked. The only remaining issues is the centering is off, I think centering is being calc first, then the window is resized. Centering should be calc after the resize to take into account the scaled window size.

**Comment by jarroddavis68** [comment]
Hmm, just so you know, RGFW_CENTER|RGFW_SCALE_TO_MONITO will not center the window and explained above. I just pulled the latest and the dpi is correct, but centering it still wrong. I have not looked at the code, and just going off what I think that is happening, the window is scaled after its centered and not taking the scale size into consideration. I can work around it, but just letting you know.

**Comment by ColleagueRiley** [comment]
@jarroddavis68 yea I moved it and it should be fixed now. I can double check the code though.

**Comment by ColleagueRiley** [comment]
Thank you for bringing up the issue. I've been planning on revisiting the monitor code for a while.

**Comment by jarroddavis68** [comment]
Oh forgot to mention that this is how i'm using RGFW in Delphi. Using the new clang based toolchain in C++ Builder I can create  and object `.o` and link then directly into Delphi. I recently added RGFW to the growing list. 
https://github.com/tinyBigGAMES/CPas
