### ISSUE TITLE
Simple Wgpu/Dawn Support?

### ISSUE THREAD

**Issue by Germ210** [ColleagueRiley/RGFW#34]
Would it be possible to make a webgpu context without directly using a raw window handle? Or at the very least make it easier to get that raw window?

**Comment by ColleagueRiley** [comment]
I don't know, I've not looked into webgpu yet.

**Comment by ColleagueRiley** [comment]
It doesn't look like it would require anything special. https://github.com/seyhajin/webgpu-wasm-c/blob/master/main.c

**Comment by ColleagueRiley** [comment]
It doesn't look like it would require anything special. https://github.com/seyhajin/webgpu-wasm-c/blob/master/main.c

**Comment by ColleagueRiley** [comment]
https://github.com/ColleagueRiley/RGFW/blob/main/examples/webgpu/webgpu.c I ported that example to RGFW.
