### ISSUE TITLE
CVDisplayLink deprecation in macOS 15

### ISSUE THREAD

**Issue by meshula** [ColleagueRiley/RGFW#36]
As of macOS 15.0, CVDisplayLink is deprecated. https://developer.apple.com/documentation/corevideo/cvdisplaylink-k0k?language=objc

```
gcc  -x c -c RGFW.h -D RGFW_NO_API -D RGFW_EXPORT -D RGFW_IMPLEMENTATION -o RGFW.o
RGFW.h:7357:3: warning: 'CVDisplayLinkCreateWithCGDisplay' is deprecated: first deprecated in macOS 15.0 - use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:)  [-Wdeprecated-declarations]
 7357 |                 CVDisplayLinkCreateWithCGDisplay(win->src.display, (CVDisplayLinkRef*)&win->src.displayLink);
      |                 ^
```

As of macOS 14.0, the replacement is on NSView. https://developer.apple.com/documentation/appkit/nsview/4191632-displaylinkwithtarget?language=objc

I was wondering if anyone's got a patch or fix in progress?

Currently one must remove -Werror from the makefile to build on Mac.

```
make examples
gcc  -Wall -Werror -Wstrict-prototypes -Wextra -Wstrict-prototypes -Wold-style-definition -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-missing-braces -Wno-missing-variable-declarations -Wno-redundant-decls -Wno-unused-function -Wno-unused-label -Wno-unused-result -Wno-incompatible-pointer-types -Wno-format -Wno-format-extra-args -Wno-implicit-function-declaration -Wno-implicit-int -Wno-pointer-sign -Wno-switch -Wno-switch-default -Wno-switch-enum -Wno-unused-value -Wno-type-limits -I. examples/basic/basic.c -lm -framework Foundation -framework AppKit -framework OpenGL -framework CoreVideo -std=c99    -o examples/basic/basic
In file included from examples/basic/basic.c:6:

./RGFW.h:7357:3: error: 'CVDisplayLinkCreateWithCGDisplay' is deprecated: first deprecated in macOS 15.0 - use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:)  [-Werror,-Wdeprecated-declarations]
 7357 |                 CVDisplayLinkCreateWithCGDisplay(win->src.display, (CVDisplayLinkRef*)&win->src.displayLink);

```

**Comment by ColleagueRiley** [comment]
> As of macOS 15.0, CVDisplayLink is deprecated
Oh, I didn't realize.

> I was wondering if anyone's got a patch or fix in progress?
A handful of people will fix the issues they find, but I'm the only person actively working on RGFW. I didn't know this was an issue so I didn't have any plans to replace it. But I will look into replacing it asap!

**Comment by meshula** [comment]
Thanks! I may have a chance to look at it in a month or two; if I do get to it before you, I'll let you know.

**Comment by ColleagueRiley** [comment]
@meshula Although this feature has been deprecated by macOS 10.15, I would like to maintain support for at least macOS 10.13. 

This just means the solution will look something like this:

```c
#ifdef MACOS_VERSION <= 10.13
// old CVDisplayLink method
#else
// new NSView method
#endif
```

**Comment by meshula** [comment]
A runtime check makes sense, although it would need a local warning suppression to be compatible with Werror.

**Comment by ColleagueRiley** [comment]
@meshula In reviewing `CVDisplayLinkRef`, I realized it might not even be needed. 

```c
CVDisplayLinkCreateWithCGDisplay(win->src.display, (CVDisplayLinkRef*)&win->src.displayLink);
CVDisplayLinkSetOutputCallback(win->src.displayLink, displayCallback, win);
CVDisplayLinkStart(win->src.displayLink);
```

The purpose is to update RGFW about changes to the display by calling back to `displayCallback`.

The callback in RGFW looks like this:

```c
CVReturn displayCallback(CVDisplayLinkRef displayLink, const CVTimeStamp* inNow, const CVTimeStamp* inOutputTime, CVOptionFlags flagsIn, CVOptionFlags* flagsOut, void* displayLinkContext) {
		RGFW_UNUSED(displayLink) RGFW_UNUSED(inNow) RGFW_UNUSED(inOutputTime) RGFW_UNUSED(flagsIn) RGFW_UNUSED(flagsOut) RGFW_UNUSED(displayLinkContext)
		return kCVReturnSuccess;
}
```

I had a lot of issues trying to figure out how to handle software rendering for MacOS, so perhaps this is leftover code from that.

I tested the examples without `CVDisplayLinkRef` and everything is working. So I think the solution is to remove CVDisplayLinkRef.

**Comment by ColleagueRiley** [comment]
This removes the `CoreVideo` dependency altogether! The issue should be fixed with the latest commits, thanks for filing the issue!
