### ISSUE TITLE
macos casting warnings with obc_msgSend (C++)

### ISSUE THREAD

**Issue by meshula** [ColleagueRiley/RGFW#37]
Looks like a further dpi qualifier might be required for the microui demo? The big blank area moves around as the window is resized. microui itself does seem anchored to the lower left.

<img width="627" alt="image" src="https://github.com/user-attachments/assets/64335162-fbf8-427c-beb3-13d958c625c2">

**Comment by ColleagueRiley** [comment]
I've not used microui outside of porting the example, so there's probably something I'm missing.

**Comment by ColleagueRiley** [comment]
Thank you for reporting these issues!

**Comment by meshula** [comment]
A quick experiment

```
/* update vertex buffer */
  vert_buf[texvert_idx + 0] = dst.x;
  vert_buf[texvert_idx + 1] = dst.y;
  vert_buf[texvert_idx + 2] = dst.x + dst.w;
  vert_buf[texvert_idx + 3] = dst.y;
  vert_buf[texvert_idx + 4] = dst.x;
  vert_buf[texvert_idx + 5] = dst.y + dst.h;
  vert_buf[texvert_idx + 6] = dst.x + dst.w;
  vert_buf[texvert_idx + 7] = dst.y + dst.h;

  for (int i = 0; i < 8; ++i) {
    vert_buf[texvert_idx + i] *= dpi; // dpi is set to 2.0f;
  }
```

looks like it's probably necessary to plumb through a multiplication throughout renderer.c. Looking at my other integrations of microui, I see that's what I did, although I did it in the draw calls, so the fix doesn't apply exactly to this demo, otherwise I'd provide a patch.

This isn't urgent for me btw, I use Dear ImGui, but was just curious to see if I could get all the demos working and bumped against this, and thought I should report it.

**Comment by ColleagueRiley** [comment]
This demo is just a slightly modified version of the [demo on the repo](https://github.com/rxi/microui) so you might also want to report any issues to their repo.

**Comment by meshula** [comment]
Hmm, there might be a general dpi related issue after all. I got the dear imgui integration going on macos, and a similar scissoring issue and the same scaling issues occur. In this case the image is scissored vertically in the middle, and the rendering coordinates again are half the mouse coordinates.

<img width="598" alt="image" src="https://github.com/user-attachments/assets/4c2362a9-04e7-4c81-b8a9-e576c550e210">

My integration is here, in case it of interest.

https://github.com/meshula/LabTemplate/tree/dear

I had to modify imgui_impl_rgfw.h slightly to deal with the latest version of clang (duplication of the RGFW_keyCodeToChar function, and the RGFW_point <=> impoint conversions don't compile), but none of those account for the dpi or scissoring issue.

**Comment by meshula** [comment]
Ok, definitely not an RGFW problem :)

```cpp
void imgui_newFrame() {
    ImGuiIO& io = ImGui::GetIO();
    io.DisplayFramebufferScale = ImVec2(2,2);

    ImGui::NewFrame();
    ImGui_ImplRgfw_NewFrame();
    ImGui_ImplOpenGL2_NewFrame();
}
```
<img width="710" alt="image" src="https://github.com/user-attachments/assets/6a0a88e0-55c6-400d-bae7-deb180a4d017">

I think what we need is 

```
float RGFW_framebuffer_scaling();
```

so one doesn't have to hard code "2".

I think with your C style message sending it might look like this:

```
		// Get the backing scale factor (for Retina displays)
		void* contentView = NSWindow_contentView(win->src.window);
		double backingScaleFactor = ((double (*)(id, SEL))objc_msgSend_fpret)(contentView, sel_registerName("backingScaleFactor"));
```

it would go right after the call to NSOpenGLView_initWithFrame.

I'm not sure what the windows and wayland variant looks like, but maybe we could start by having a routine return 1.0 for them, and perhaps the community might contribute the appropriate code to fill it in?

**Comment by ColleagueRiley** [comment]
Why not use the scale factor from the monitor?

	RGFW_monitor monitor = RGFW_window_getMonitor();

monitor.scaleX;
monitor.scaleY;

**Comment by meshula** [comment]
Why not? :) Somehow in my searching through the header I wasn't able to find it. That works, thanks! Closing this issue as everything seems to be in place. Scaling microui isn't a top priority for me, and as you say, microui needs a scaling facility. Thanks for looking at it with me.

**Comment by meshula** [comment]
There isn't scaling code in the dear imgui example. I can have a go. I'll reopen this issue :)

**Comment by meshula** [comment]
Getting the dear imgui example up and running on mac is a fair amount of work due to the lack of casting in the RGFW.h file. On mac/clang, we need to activate c++11 or greater to enable constexpr on mac, but that of course causes a cascade of casting errors in RGFW.h (see below for one of hundreds, I'm sure you're aware already of course). One solution, as documented would be to create RGFW.m which instantiates RGFW, and add a bunch of ifdef's to main.cpp to conditionally define RGFW or not per platform. It gets to be a bit more work though, because the imgui_impl_rgfw header is where rgfw itself is instantiated. These changes seem a bit contrary to the spirit of an easy to include single header library though.

example casting issue:

```
./RGFW.h:5738:31: error: cannot initialize a parameter of type 'SEL' with an lvalue of type 'void *'
 5738 |                 objc_msgSend_void_id(image, func, imageRep);
```

I'm wondering if it might be worth biting the bullet and adding all the casting, so that RGFW.h Just Works when included? I started to have a go, but there's so much to do, it doesn't seem worth attempting without further discussion.

One thought I had while starting on it was that life might be easier if that code was written in ObjC, and it would make it easier to reason about object lifetime because the code when then be subject to the same rules as the rest of one's program.

From comments in the code by EimaMei I suppose there may be philosophical reasons why C is strictly used in the wrapper; so given that, I'd have to suggest a next step would be to add casting to satisfy the compiler's desire to type check the pointers.

**Comment by ColleagueRiley** [comment]
It's written in purely C so it can be used without anything special, like a normal single-header file. The casting issues should be able to be fixed with normal C casting and make sure types are properly used. 

I wasn't aware of these issues because I've not compiled RGFW using C++ on macOS.

Creating an RGFW.m file would not fix this issue, considering you could just compile RGFW.h to an RGFW.o, and then this issue wouldn't happen anyway.

**Comment by meshula** [comment]
> considering you could just compile RGFW.h to an RGFW.o

Ah, via the makefile. I haven't used make for literal decades, thanks for pointing that out.

> The casting issues should be able to be fixed with normal C casting and make sure types are properly used.

That's what I was trying to say, and pointing out that the amount of work to do that is rather large.

**Comment by ColleagueRiley** [comment]
> Ah, via the makefile. I haven't used make for literal decades, thanks for pointing that out.
Or whatever build system you want, it's not hard to compile RGFW!

> That's what I was trying to say, and pointing out that the amount of work to do that is rather large.
Most of it could probably be automated with find/replace. I'd rather do that than compromise on a big part of my project.

**Comment by meshula** [comment]
Created the PR with the simple fixes we discussed above. (https://github.com/ColleagueRiley/imgui_imp_rgfw.h/pull/1/files) There's a note there about two bugs; one simple (mouse position seems double scaled), one not so obvious (mouse clicks stick after playing with the UI for a bit). Unfortunately I've got limited time on this, so I'll update the PR as I find time to work on those two issues.

**Comment by ColleagueRiley** [comment]
@meshula The casting issues should be fixed with the latest commit (https://github.com/ColleagueRiley/RGFW/commit/cbd2838e55745c6ac2fe6c252c26bb44b7166263).
