### ISSUE TITLE
RGFW_vulkan vulkWin does not have window member.

### ISSUE THREAD

**Issue by TheLastVoyager** [ColleagueRiley/RGFW#41]
#ifdef RGFW_WINDOWS
        VkWin32SurfaceCreateInfoKHR win32 = {VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR, 0, 0, GetModuleHandle(NULL), 
    vulkWin->window};

        vkCreateWin32SurfaceKHR(RGFW_vulkan_info.instance, &win32, NULL, &vulkWin->rSurf);'
    #endif

The problem is on line 134 of RGFW_vulkan.h, where if you compile you get an error saying "vulkWin does not have a member named window". A simple fix I have done is as below.

    #ifdef RGFW_WINDOWS
        VkWin32SurfaceCreateInfoKHR win32 = {VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR, 0, 0, 
    GetModuleHandle(NULL), (HWND)win->src.window};

        vkCreateWin32SurfaceKHR(RGFW_vulkan_info.instance, &win32, NULL, &vulkWin->rSurf);
    #endif

Atleast it compiles, but not sure whether it works. This problem also is present on the MacOS define.

    #if defined(RGFW_MACOS) && !defined(RGFW_MACOS_X11)
        VkMacOSSurfaceCreateFlagsMVK macos = {VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK, 0, 0, vulkWin->display, 
    vulkWin->window};

        vkCreateMacOSSurfaceMVK(RGFW_vulkan_info.instance, &macos, NULL, &vulkWin->rSurf);
    #endif

Hopefully this issue is solved.

**Comment by ColleagueRiley** [comment]
If that solves the issue do you mind making a PR?

**Comment by TheLastVoyager** [comment]
Sure, I will do it ASAP, but i am still not sure whether it works properly, I will do some testing as well.

**Comment by TheLastVoyager** [comment]
I've already submitted a pull request for the change towards RGFW_vulkan.h

**Comment by ColleagueRiley** [comment]
@TheLastVoyager Thank you!

**Comment by TheLastVoyager** [comment]
@ColleagueRiley Ur Welcome
