### ISSUE TITLE
resize values doesn't change until window is moved

### ISSUE THREAD

**Issue by DarekParodia** [ColleagueRiley/RGFW#46]
I found an issue where values for resize event are the same until the window is moved somewhere. I'm not sure if this is a bug or a feature but here is the video of running callbacks example:

https://github.com/user-attachments/assets/d8808a1a-3b47-452d-87bb-49afbcef1756

also the first values that are being printed are a bit off.
this is my setup:
![image](https://github.com/user-attachments/assets/33bc6169-32d5-403e-b56d-4174160f12cb)

**Comment by ColleagueRiley** [comment]
@DarekParodia Oh, this is a silly copy/paste mistake on my part.  I copied and pasted the code for the window move callback but did not change the function to print the width and height. 
 
This commit (https://github.com/ColleagueRiley/RGFW/commit/377874b47b1f9f0e567c0468e6e1ea417d7eceaa) should fix the issue.
