### ISSUE TITLE
RGFW windows are not raised (?) initially on macOS

### ISSUE THREAD

**Issue by OleksiyPuzikov** [ColleagueRiley/RGFW#48]
This is a little bit harder to describe, but when launched from terminal, the window will have the coloured window controls grayed out.

Clicking on the window won't make them coloured, but mouse hover would.

Fix - select another window and then get back to RGFW example - now window decorations are OK.

M1, Sequoia 15.1.1

**Comment by ColleagueRiley** [comment]
I'm looking into this issue currently. The window does seem to be raised properly other than the grayed-out controls. I'm confused about what's causing this behavior...

**Comment by OleksiyPuzikov** [comment]
Something I'm using in my Tk Python code is as following:

```
import os
from Cocoa import NSRunningApplication, NSApplicationActivateIgnoringOtherApps

app = NSRunningApplication.runningApplicationWithProcessIdentifier_(os.getpid())
app.activateWithOptions_(NSApplicationActivateIgnoringOtherApps)
```

but that might as well be something in your message loop?

**Comment by ColleagueRiley** [comment]
@OleksiyPuzikov The issue seemed to be some missing calls to [`sendEvent`](https://developer.apple.com/documentation/appkit/nsapplication/sendevent(_:)) and [`updateWindows`](https://developer.apple.com/documentation/appkit/nsapplication/updatewindows()). The most recent commits should fix it! Thank you for filing this issue.
