### ISSUE TITLE
Lagging scroll value (Linux / X11)

### ISSUE THREAD

**Issue by dairin0d** [ColleagueRiley/RGFW#57]
On Linux, I noticed that the `win->event.scroll` value "lags" by 1 event. It seems that this is due to scroll direction being calculated based on `win->event.button` before it is actually assigned the new value (when I tried to move the `win->event.button = E.xbutton.button;` line before the `switch(win->event.button) { case RGFW_mouseScrollUp: ...` block, the odd behavior disappeared).

**Comment by ColleagueRiley** [comment]
@dairin0d Thanks for filing this issue. It looks like I checked the value of `win->event.button` before it was checked rather than after. Thank you for pointing out the typo! This commit (https://github.com/ColleagueRiley/RGFW/commit/0e7985c1a7621fa14d2f7e45393c34cd00103d40) should fix it.

**Comment by dairin0d** [comment]
Yup, the fix works. Thanks!
