### ISSUE TITLE
When enabling raw input mode, set _lastMousePoint to the screen center (Linux / X11)

### ISSUE THREAD

**Issue by dairin0d** [ColleagueRiley/RGFW#58]
On Linux, when "mouse hold" (raw input) mode is enabled, the first `win->event.point` value after that contains a sudden jump. This seems to be due to the mouse being moved to the center of the window, but the `win->_lastMousePoint` not being set to the same value. When I added `win->_lastMousePoint = RGFW_POINT(win->r.w / 2, win->r.h / 2);` to the end of `void RGFW_window_mouseHold(...)`, the problem no longer manifested.

By the way (out of curiosity): I noticed that in the X11 version of `RGFW_window_checkEvent()`, the `MotionNotify` case contains this odd code block:
```
win->event.point.x = E.xmotion.x;
win->event.point.y = E.xmotion.y;

if ((win->_winArgs & RGFW_HOLD_MOUSE)) {
	win->event.point.y = E.xmotion.y;

	win->event.point.x = win->_lastMousePoint.x - abs(win->event.point.x);
	win->event.point.y = win->_lastMousePoint.y - abs(win->event.point.y);
}

win->_lastMousePoint = RGFW_POINT(E.xmotion.x, E.xmotion.y);
```
Is this deliberate, or just a leftover of some debug logic? It seems like subtracting `E.xmotion` from `win->_lastMousePoint` would have worked just as well (and I haven't yet noticed any problems in practice when I simplified the contents of the if block that way) 🤔

**Comment by ColleagueRiley** [comment]
@dairin0d These should be fixed with the latest commits.

**Comment by dairin0d** [comment]
Now everything seems to work well on Linux. Thanks!
