### ISSUE TITLE
Stack around the variable 'charBuffer' was corrupted (Windows 10/11)

### ISSUE THREAD

**Issue by Aionios** [ColleagueRiley/RGFW#59]
I have encountered an issue with x64 windows build.
In `RGFW_window_checkEvent()` some `switch` cases have the local variable `i16 charBuffer`.
![image](https://github.com/user-attachments/assets/b0fbf74b-156a-4171-ad98-445d02890bf7)
The `ToUnicodeEx()` writes 2 `wchar_t`s (4 bytes), so I think the fifth argument should be 1 instead of 2.
![image](https://github.com/user-attachments/assets/93b79b4e-2f3a-42c4-afee-91ac9b050983)

**Comment by ColleagueRiley** [comment]
@Aionios If it's `wchar_ts` (4 bytes), shouldn't charBuffer be u32 instead of u16 (in addition to only requesting 1 wchar_ts)?

**Comment by Aionios** [comment]
@ColleagueRiley Sorry, I am not familiar with the win32 Unicode APIs😅. Just happened to find this memory issue.

**Comment by ColleagueRiley** [comment]
@Aionios That's okay, I was just wondering if you had any input on that.

The problem should be fixed now anyway!
